website_bundle_partial:
    path:     /static/partial
    defaults: { _controller: WebsiteBundle:Static:partial }

website_bundle_template:
    path:     /static/{slug}
    defaults: { _controller: WebsiteBundle:Static:template }
