
parameters:

    web_components.globals:
        example: ral
        site_title: Website Name
        page_desc: Description of the site
        site_headline: A Cool Headline
        favicon_path: path/to/site/favicons
        callrail_required: false
        includes: []
        service.search_provider: 'web_components.search_provider'
        sites: 
            -
                bundle: RALSiteBundle
                host:   www.ral.dev

        content_types:
            default: page
            post:
                repository: 'web_components.content.post'

            page:
                repository: 'web_components.content.page'
                with: 
                    - ['post:view', [ slug, category ] ]
                viewless: false
                templates:
                    list: '::LandingPage:index.html.twig'
                    view: '::Blog:read.html.twig'
                ajax: true
                defaults:
                    action: list
                    category: default

        config.search:
            searchable: [ 'page' ]
            templates:
                index: ''
                results: ''
            ajax: true   




services:
    web_components.twig:
        class: WebComponents\SiteBundle\Twig\TwigExtension
        calls: 
            - [ setContainer,  [ "@service_container" ] ]
            - [ setRouteService, [ "@router" ] ]
            - [ setImageFactory, [ "@web_components.elements.image" ] ]
        tags:
            - { name: twig.extension }
    web_components.elements.image:
        class: WebComponents\SiteBundle\Elements\Image\ImageFactory

    web_components.content.page:
        class: WebComponents\SiteBundle\Page\PageRepository

    web_components.content.post:
        class: WebComponents\SiteBundle\Post\PostRepository     

    web_components.search_provider:
        class: Quallsbenson\WebComponents\Search\SearchProvider
        arguments: [ '@web_components.search_result_provider', '@web_components.search_result_filter' ]

    web_components.search_result_provider:
        class: Quallsbenson\WebComponents\Search\SearchResultProviderFactory

    web_components.search_result_filter:
        class: Quallsbenson\WebComponents\Search\SearchResultFilter