
parameters:
    web_components.globals:
        example: example
        site_title: Website Name
        site_headline: A Cool Headline
        favicon_path: path/to/site/favicons
        callrail_required: false
        sites: []

        content_types:
            default: page
            post:
                repository: 'web_components.content.post'

            page:
                repository: 'web_components.content.page'
                with: [ 'post:list' ]
                viewless: false
                templates:
                    list: '::x:index.html.twig'
                    view: '::Blog:read.html.twig'
                ajax: true
                defaults:
                    action: list
                    category: magazines




services:
    web_components.twig:
        class: WebComponents\SiteBundle\Twig\TwigExtension
        calls: 
            - [ setContainer,  [ "@service_container" ] ]
            - [ setRouteService, [ "@router" ] ]
            - [ setImageFactory, [ "@web_components.elements.image" ] ]
        tags:
            - { name: twig.extension }
    web_components.elements.image:
        class: WebComponents\SiteBundle\Elements\Image\ImageFactory

    web_components.content.page:
        class: WebComponents\SiteBundle\Page\PageRepository

    web_components.content.post:
        class: WebComponents\SiteBundle\Content\Post\PostRepository        